;this file for FamiTone2 library generated by text2data tool

yun_music_data:
	.byte 9
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,307,256
	.word @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,307,256
	.word @song8ch0,@song8ch1,@song8ch2,@song8ch3,@song8ch4,307,256

@instruments:
	.byte $30 ;instrument $00
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env1,@env0,@env31
	.byte $00
	.byte $30 ;instrument $02
	.word @env2,@env0,@env31
	.byte $00
	.byte $30 ;instrument $04
	.word @env13,@env29,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env18,@env0,@env0
	.byte $00
	.byte $30 ;instrument $06
	.word @env15,@env0,@env0
	.byte $00
	.byte $30 ;instrument $07
	.word @env9,@env0,@env0
	.byte $00
	.byte $30 ;instrument $08
	.word @env16,@env0,@env0
	.byte $00
	.byte $30 ;instrument $09
	.word @env11,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env4,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0b
	.word @env5,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0c
	.word @env7,@env0,@env0
	.byte $00
	.byte $30 ;instrument $0d
	.word @env12,@env25,@env0
	.byte $00
	.byte $30 ;instrument $0e
	.word @env3,@env27,@env0
	.byte $00
	.byte $30 ;instrument $0f
	.word @env6,@env0,@env0
	.byte $00
	.byte $30 ;instrument $10
	.word @env3,@env26,@env0
	.byte $00
	.byte $30 ;instrument $11
	.word @env3,@env28,@env0
	.byte $00
	.byte $30 ;instrument $12
	.word @env10,@env30,@env0
	.byte $00
	.byte $b0 ;instrument $13
	.word @env8,@env0,@env0
	.byte $00
	.byte $30 ;instrument $14
	.word @env17,@env0,@env0
	.byte $00
	.byte $30 ;instrument $15
	.word @env14,@env29,@env0
	.byte $00
	.byte $30 ;instrument $1b
	.word @env24,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $1d
	.word @env21,@env0,@env0
	.byte $00
	.byte $30 ;instrument $1e
	.word @env22,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $21
	.word @env19,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $22
	.word @env20,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $28
	.word @env23,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c1,$c2,$c3,$c6,$00,$03
@env2:
	.byte $cf,$00,$00
@env3:
	.byte $c6,$c6,$c5,$c4,$c3,$09,$c2,$08,$c1,$0f,$c0,$00,$0a
@env4:
	.byte $ca,$c8,$c6,$c4,$c2,$c1,$c0,$00,$06
@env5:
	.byte $ca,$c9,$c7,$c4,$c2,$c0,$00,$05
@env6:
	.byte $cc,$ca,$c9,$c7,$c6,$c5,$c4,$c4,$c3,$c3,$c2,$02,$c1,$03,$c9,$c7
	.byte $c6,$c5,$c4,$c3,$02,$c2,$03,$c1,$02,$c4,$c3,$c3,$c2,$03,$c1,$04
	.byte $c0,$00,$20
@env7:
	.byte $c0,$c1,$c2,$c4,$c5,$c6,$03,$c4,$c3,$c2,$03,$c2,$00,$0b
@env8:
	.byte $c1,$c2,$c3,$c4,$00,$03
@env9:
	.byte $cf,$cd,$cb,$c9,$c7,$c6,$c5,$c4,$c3,$06,$c3,$00,$0a
@env10:
	.byte $c8,$00,$00
@env11:
	.byte $ce,$cd,$cc,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$c4,$c3,$c2,$c6,$c5,$c4
	.byte $c4,$c3,$c2,$c2,$c1,$c0,$0a,$c2,$c3,$c2,$c2,$c1,$04,$c0,$00,$1d
@env12:
	.byte $c2,$c3,$c5,$c6,$c7,$c8,$c9,$03,$c8,$c6,$c4,$c8,$c8,$c8,$00,$0d
@env13:
	.byte $cf,$cd,$cb,$c9,$c7,$c5,$c3,$c1,$c0,$00,$08
@env14:
	.byte $c9,$c7,$c6,$c4,$c3,$c2,$c1,$c0,$00,$07
@env15:
	.byte $ca,$c5,$c3,$c2,$c0,$00,$04
@env16:
	.byte $cf,$cf,$ce,$ce,$cd,$cb,$c6,$c5,$c3,$c3,$c2,$c2,$c1,$02,$c1,$00
	.byte $0e
@env17:
	.byte $cb,$c9,$c7,$c5,$c4,$c2,$c1,$c1,$c0,$00,$08
@env18:
	.byte $cd,$cc,$ca,$c9,$c7,$c6,$c5,$c3,$c0,$00,$08
@env19:
	.byte $cf,$ce,$cd,$cb,$ca,$c9,$c8,$c7,$c6,$c5,$03,$c4,$03,$c3,$03,$c2
	.byte $04,$c1,$03,$c0,$00,$13
@env20:
	.byte $c4,$c6,$c7,$c8,$c8,$c7,$c6,$02,$c5,$02,$c4,$02,$c4,$00,$0c
@env21:
	.byte $cf,$cb,$c9,$c7,$c5,$c4,$c3,$c3,$c2,$02,$c1,$c1,$c0,$00,$0c
@env22:
	.byte $cf,$cf,$ce,$ce,$cd,$cb,$c6,$c5,$c3,$c3,$c2,$04,$c2,$00,$0c
@env23:
	.byte $c2,$c5,$c6,$c7,$c8,$05,$c7,$c6,$c5,$02,$c5,$00,$0a
@env24:
	.byte $cf,$cc,$c8,$c7,$c4,$c3,$c2,$c1,$c0,$00,$08
@env25:
	.byte $c0,$cc,$cc,$c0,$00,$03
@env26:
	.byte $c0,$02,$c3,$02,$c7,$c7,$c7,$00,$00
@env27:
	.byte $c0,$02,$c4,$02,$c7,$c7,$c7,$00,$00
@env28:
	.byte $c0,$02,$c3,$02,$c8,$c8,$c8,$00,$00
@env29:
	.byte $c7,$c3,$c0,$bd,$00,$02
@env30:
	.byte $cc,$c0,$00,$01
@env31:
	.byte $c0,$0b,$c1,$c2,$c3,$c4,$c3,$c2,$c1,$c0,$00,$02


@song0ch0:
	.byte $fb,$06
@ref0:
	.byte $8c,$33,$35,$33,$35,$33,$35,$33,$35,$33,$35,$33,$35,$33,$35,$33
	.byte $35,$32,$9b,$00,$9f
@song0ch0loop:
@ref1:
	.byte $81
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@ref2:
	.byte $9f,$8c,$59,$5b,$59,$5b,$59,$5b,$59,$5b,$58,$99,$00,$a1
@song0ch1loop:
@ref3:
	.byte $81
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@ref4:
	.byte $80,$32,$8d,$22,$85,$28,$85,$32,$8d,$22,$85,$28,$85,$22,$97,$00
	.byte $a3
@song0ch2loop:
@ref5:
	.byte $81
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@ref6:
	.byte $88,$21,$21,$86,$21,$88,$21,$21,$21,$86,$21,$88,$21,$21,$21,$86
	.byte $21,$88,$21,$21,$21,$86,$21,$88,$21,$20,$bd
@song0ch3loop:
@ref7:
	.byte $81
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@ref8:
	.byte $f9,$85
@song0ch4loop:
@ref9:
	.byte $81
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@ref10:
	.byte $8c,$31,$33,$31,$33,$31,$33,$31,$33,$39,$3b,$39,$3b,$39,$3b,$39
	.byte $3b,$32,$9b,$00,$81
@song1ch0loop:
@ref11:
	.byte $e1
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@ref12:
	.byte $80,$32,$8d,$30,$8d,$3a,$8d,$38,$8d,$8c,$38,$9b,$00,$81
@song1ch1loop:
@ref13:
	.byte $e1
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@ref14:
	.byte $80,$4b,$01,$4b,$01,$32,$85,$01,$33,$53,$01,$53,$01,$38,$85,$00
	.byte $85,$8c,$40,$9b,$00,$81
@song1ch2loop:
@ref15:
	.byte $e1
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@ref16:
	.byte $88,$03,$8a,$1f,$1f,$1f,$86,$0d,$8a,$1f,$1f,$88,$03,$03,$8a,$1f
	.byte $1f,$1f,$86,$0d,$8a,$1f,$1f,$1e,$a3
@song1ch3loop:
@ref17:
	.byte $e1
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@ref18:
	.byte $e1
@song1ch4loop:
@ref19:
	.byte $e1
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$0d
@song2ch0loop:
@ref20:
	.byte $8c,$2c,$9d,$2c,$9d
@ref21:
	.byte $44,$9d,$44,$9d
@ref22:
	.byte $2c,$9d,$2c,$9d
@ref23:
	.byte $2c,$9d,$2c,$9d
@ref24:
	.byte $2c,$8d,$2c,$8d,$2c,$8d,$2c,$8d,$2c,$8d
@ref25:
	.byte $2c,$8d,$26,$9d,$2a,$89,$2d,$2a,$85,$26,$85
@ref26:
	.byte $2c,$9d,$2c,$8d,$2c,$85,$2e,$85
@ref27:
	.byte $32,$8d,$1a,$8d,$32,$8d,$1a,$8d
@ref28:
	.byte $32,$85,$24,$85,$3c,$85,$24,$85,$40,$85,$33,$3d,$36,$8d
@ref29:
	.byte $8f,$2c,$8d,$3a,$8d,$3c,$8d
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@song2ch1loop:
@ref30:
	.byte $00,$bd
@ref31:
	.byte $bf
@ref32:
	.byte $8c,$3a,$85,$37,$3b,$3d,$3a,$89,$00,$9d
@ref33:
	.byte $3a,$85,$45,$3d,$41,$3d,$3a,$85,$00,$9d
@ref34:
	.byte $4e,$85,$4c,$95,$4e,$85,$4c,$95,$52,$85,$4e,$85
@ref35:
	.byte $4c,$85,$48,$85,$4e,$9d,$52,$9d
@ref36:
	.byte $44,$91,$3b,$3d,$37,$44,$8b,$46,$44,$8d
@ref37:
	.byte $3a,$9d,$3a,$9d
@ref38:
	.byte $82,$3d,$25,$2d,$25,$3d,$25,$2d,$25,$00,$89,$8c,$24,$91
@ref39:
	.byte $82,$2c,$85,$3c,$85,$3a,$85,$36,$85,$3c,$85,$40,$85,$3c,$85,$3a
	.byte $85
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@song2ch2loop:
@ref40:
	.byte $80,$44,$9d,$2c,$9d
@ref41:
	.byte $2c,$9d,$2c,$83,$00,$22,$83,$00,$24,$83,$00,$1e,$83,$00
@ref42:
	.byte $2c,$bd
@ref43:
	.byte $22,$85,$1f,$23,$25,$28,$85,$25,$22,$9d
@ref44:
	.byte $2c,$8d,$2c,$2e,$2c,$2e,$2c,$2e,$2c,$2e,$2c,$8d,$2c,$2e,$2c,$2e
	.byte $2c,$2e,$2c,$2e,$2c,$85,$2e,$85
@ref45:
	.byte $28,$85,$1e,$85,$36,$9d,$22,$9d
@ref46:
	.byte $2c,$8d,$3a,$85,$3c,$85,$2c,$8d,$40,$85,$3c,$85
@ref47:
	.byte $22,$9d,$32,$83,$00,$2e,$83,$00,$28,$83,$00,$22,$83,$00
@ref48:
	.byte $32,$9d,$28,$85,$24,$85,$1e,$8d
@ref49:
	.byte $2c,$bd
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@song2ch3loop:
@ref50:
	.byte $88,$21,$8a,$1f,$86,$09,$8a,$1e,$1e,$88,$20,$8a,$1e,$88,$21,$86
	.byte $09,$8a,$1e,$1e,$88,$21,$8a,$1f,$86,$09,$8a,$1e,$1e,$88,$20,$8a
	.byte $1e,$88,$21,$86,$09,$8a,$1e,$1e
	.byte $ff,$16
	.word @ref50
	.byte $ff,$16
	.word @ref50
	.byte $ff,$16
	.word @ref50
@ref54:
	.byte $8e,$14,$85,$15,$88,$21,$86,$1e,$1e,$88,$20,$8a,$1e,$88,$20,$8a
	.byte $1e,$88,$20,$8a,$1e,$8e,$14,$85,$15,$88,$21,$86,$1e,$1e,$88,$20
	.byte $8a,$1e,$88,$20,$8a,$1e,$88,$20,$8a,$1e,$8e,$14,$85,$14,$85
@ref55:
	.byte $14,$85,$14,$85,$88,$21,$8a,$1f,$86,$09,$8a,$1e,$1e,$88,$20,$8a
	.byte $1e,$88,$21,$86,$09,$8a,$1e,$1e,$8e,$15,$8a,$1f,$86,$09,$8a,$1e
	.byte $1e,$88,$20,$8a,$1e,$88,$21,$86,$09,$8a,$1e,$1e
	.byte $ff,$16
	.word @ref50
	.byte $ff,$16
	.word @ref50
	.byte $ff,$16
	.word @ref50
	.byte $ff,$16
	.word @ref50
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@song2ch4loop:
@ref60:
	.byte $bf
@ref61:
	.byte $bf
@ref62:
	.byte $bf
@ref63:
	.byte $bf
@ref64:
	.byte $cf
@ref65:
	.byte $cf
@ref66:
	.byte $bf
@ref67:
	.byte $bf
@ref68:
	.byte $bf
@ref69:
	.byte $bf
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$0a
@ref70:
	.byte $8c,$32,$bd
@ref71:
	.byte $bf
@song3ch0loop:
@ref72:
	.byte $92,$5c,$62,$6a,$92,$62,$6a,$94,$62,$8c,$5c,$62,$6a,$92,$62,$6a
	.byte $94,$62,$6a,$85,$8c,$5c,$60,$6a,$92,$60,$6a,$94,$60,$8c,$5c,$66
	.byte $6a,$92,$66,$6a,$94,$66,$6a,$85
@ref73:
	.byte $8c,$5c,$62,$6a,$92,$62,$6a,$94,$62,$8c,$5c,$62,$6a,$92,$62,$6a
	.byte $94,$62,$6a,$85,$8c,$5c,$60,$6a,$92,$60,$6a,$94,$60,$8c,$5c,$66
	.byte $6a,$92,$66,$6a,$94,$66,$6a,$85
	.byte $ff,$1c
	.word @ref73
	.byte $ff,$1c
	.word @ref73
@ref76:
	.byte $8c,$60,$6a,$6e,$92,$6a,$6e,$94,$6a,$8c,$60,$6a,$70,$92,$6a,$70
	.byte $94,$6a,$70,$85,$8c,$5c,$64,$6a,$92,$64,$6a,$94,$64,$8c,$5c,$64
	.byte $6e,$92,$64,$6e,$94,$64,$6e,$85
	.byte $ff,$1c
	.word @ref76
	.byte $ff,$1c
	.word @ref76
	.byte $ff,$1c
	.word @ref76
	.byte $ff,$1c
	.word @ref73
	.byte $ff,$1c
	.word @ref73
	.byte $ff,$1c
	.word @ref73
	.byte $ff,$1c
	.word @ref73
	.byte $ff,$1c
	.word @ref76
	.byte $ff,$1c
	.word @ref76
	.byte $ff,$1c
	.word @ref76
	.byte $ff,$1c
	.word @ref76
@ref88:
	.byte $8c,$5c,$64,$6a,$92,$64,$6a,$94,$64,$8c,$5c,$64,$6e,$92,$64,$6e
	.byte $94,$64,$6e,$85,$8c,$56,$5c,$6a,$92,$5c,$6a,$94,$5c,$8c,$56,$5c
	.byte $64,$92,$5c,$64,$94,$5c,$64,$85
	.byte $ff,$1c
	.word @ref88
	.byte $ff,$1c
	.word @ref88
	.byte $ff,$1c
	.word @ref88
@ref92:
	.byte $00,$bd
@ref93:
	.byte $af,$8c,$44,$92,$44,$94,$44,$85,$5c,$92,$5c
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@ref94:
	.byte $00,$bd
@ref95:
	.byte $bf
@song3ch1loop:
@ref96:
	.byte $96,$44,$b9,$40,$81
@ref97:
	.byte $44,$ad,$00,$89,$40,$81
@ref98:
	.byte $44,$b9,$40,$81
	.byte $ff,$06
	.word @ref97
@ref100:
	.byte $49,$3a,$85,$49,$3a,$85,$48,$85,$4d,$48,$85,$4f,$4f,$4d,$49,$4c
	.byte $81
@ref101:
	.byte $49,$3a,$85,$49,$3a,$85,$48,$85,$45,$40,$85,$3a,$85,$41,$3b,$40
	.byte $81
	.byte $ff,$11
	.word @ref100
	.byte $ff,$11
	.word @ref101
@ref104:
	.byte $44,$b9,$40,$81
	.byte $ff,$06
	.word @ref97
@ref106:
	.byte $44,$b9,$40,$81
	.byte $ff,$06
	.word @ref97
	.byte $ff,$11
	.word @ref100
	.byte $ff,$11
	.word @ref101
	.byte $ff,$11
	.word @ref100
	.byte $ff,$11
	.word @ref101
@ref112:
	.byte $98,$45,$3b,$43,$44,$91,$52,$85,$4e,$85,$4d,$49,$45,$48,$81
@ref113:
	.byte $45,$3b,$43,$44,$91,$52,$85,$4e,$85,$56,$85,$52,$85
@ref114:
	.byte $45,$3b,$43,$44,$91,$52,$85,$4e,$85,$4d,$49,$45,$48,$81
	.byte $ff,$0d
	.word @ref113
	.byte $ff,$04
	.word @ref96
	.byte $ff,$06
	.word @ref97
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@ref118:
	.byte $80,$14,$89,$1a,$91,$18,$89,$1e,$91
@ref119:
	.byte $14,$89,$1a,$91,$18,$89,$1f,$00,$8d
@song3ch2loop:
	.byte $ff,$08
	.word @ref118
	.byte $ff,$09
	.word @ref119
@ref122:
	.byte $14,$89,$1a,$91,$18,$89,$1e,$91
	.byte $ff,$09
	.word @ref119
@ref124:
	.byte $18,$89,$22,$91,$2c,$85,$1d,$14,$8d,$2c,$81
	.byte $ff,$0b
	.word @ref124
	.byte $ff,$0b
	.word @ref124
	.byte $ff,$0b
	.word @ref124
	.byte $ff,$08
	.word @ref122
	.byte $ff,$09
	.word @ref119
	.byte $ff,$08
	.word @ref122
	.byte $ff,$09
	.word @ref119
	.byte $ff,$0b
	.word @ref124
	.byte $ff,$0b
	.word @ref124
	.byte $ff,$0b
	.word @ref124
	.byte $ff,$0b
	.word @ref124
@ref136:
	.byte $15,$23,$1d,$15,$23,$1d,$14,$85,$0f,$15,$1d,$0f,$15,$1d,$23,$26
	.byte $81
	.byte $ff,$11
	.word @ref136
	.byte $ff,$11
	.word @ref136
	.byte $ff,$11
	.word @ref136
	.byte $ff,$08
	.word @ref122
	.byte $ff,$09
	.word @ref119
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@ref142:
	.byte $bf
@ref143:
	.byte $88,$20,$8a,$0e,$88,$20,$8a,$0a,$86,$08,$8a,$0a,$88,$20,$86,$04
	.byte $88,$20,$86,$04,$88,$20,$8a,$08,$86,$20,$8a,$0e,$12,$16,$88,$20
	.byte $8a,$0e,$88,$20,$8a,$0a,$86,$08,$8a,$0a,$88,$20,$86,$04,$88,$20
	.byte $86,$04,$88,$20,$8a,$08,$86,$20,$8a,$0e,$12,$16
@song3ch3loop:
@ref144:
	.byte $88,$20,$8a,$0e,$88,$20,$8a,$0a,$86,$08,$8a,$0a,$88,$20,$86,$04
	.byte $88,$20,$86,$04,$88,$20,$8a,$08,$86,$20,$8a,$0e,$12,$16,$88,$20
	.byte $8a,$0e,$88,$20,$8a,$0a,$86,$08,$8a,$0a,$88,$20,$86,$04,$88,$20
	.byte $86,$04,$88,$20,$8a,$08,$86,$20,$08,$20,$08
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
	.byte $ff,$20
	.word @ref144
@ref165:
	.byte $88,$20,$8a,$0e,$88,$20,$8a,$0a,$86,$08,$8a,$0a,$88,$20,$86,$04
	.byte $88,$20,$86,$04,$88,$20,$8a,$08,$86,$20,$8a,$0e,$12,$16,$88,$20
	.byte $8a,$0e,$88,$20,$8a,$0a,$86,$08,$8a,$0a,$88,$20,$86,$04,$20,$85
	.byte $8a,$0f,$0e,$81
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@ref166:
	.byte $bf
@ref167:
	.byte $bf
@song3ch4loop:
@ref168:
	.byte $bf
@ref169:
	.byte $bf
@ref170:
	.byte $bf
@ref171:
	.byte $bf
@ref172:
	.byte $bf
@ref173:
	.byte $bf
@ref174:
	.byte $bf
@ref175:
	.byte $bf
@ref176:
	.byte $bf
@ref177:
	.byte $bf
@ref178:
	.byte $bf
@ref179:
	.byte $bf
@ref180:
	.byte $bf
@ref181:
	.byte $bf
@ref182:
	.byte $bf
@ref183:
	.byte $bf
@ref184:
	.byte $bf
@ref185:
	.byte $bf
@ref186:
	.byte $bf
@ref187:
	.byte $bf
@ref188:
	.byte $bf
@ref189:
	.byte $bf
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$0b
@ref190:
	.byte $8c,$32,$34,$32,$34,$33,$34,$81
@ref191:
	.byte $3b,$35,$33,$2e,$81
@song4ch0loop:
@ref192:
	.byte $8c,$4a,$8f,$4c,$52,$4c,$4b,$47,$4a,$8f,$4c,$52,$4c,$4b,$52,$81
@ref193:
	.byte $54,$8f,$54,$5a,$54,$53,$4f,$52,$8d,$4a,$89,$46,$81
@ref194:
	.byte $4a,$8f,$4c,$52,$4c,$4b,$47,$4a,$8f,$4c,$52,$4c,$4b,$52,$81
	.byte $ff,$0d
	.word @ref193
@ref196:
	.byte $32,$34,$32,$34,$33,$35,$3b,$35,$33,$2f,$32,$91,$2b,$29,$24,$81
@ref197:
	.byte $28,$91,$2b,$33,$2b,$28,$9d
	.byte $ff,$10
	.word @ref196
	.byte $ff,$07
	.word @ref197
@ref200:
	.byte $90,$58,$85,$55,$4b,$59,$5b,$61,$5b,$58,$85,$55,$4b,$58,$5a,$58
	.byte $5a,$61,$5a,$81
@ref201:
	.byte $62,$85,$61,$59,$62,$85,$61,$59,$59,$5b,$59,$5b,$61,$5b,$59,$54
	.byte $81
@ref202:
	.byte $58,$85,$55,$4b,$59,$5b,$61,$5b,$58,$85,$55,$4b,$58,$5a,$58,$5a
	.byte $61,$5a,$81
	.byte $ff,$11
	.word @ref201
@ref204:
	.byte $8c,$32,$34,$32,$34,$33,$35,$3b,$35,$33,$2f,$32,$91,$2b,$29,$24
	.byte $81
	.byte $ff,$07
	.word @ref197
	.byte $ff,$10
	.word @ref196
	.byte $ff,$07
	.word @ref197
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@ref208:
	.byte $8c,$1a,$8d
@ref209:
	.byte $8f
@song4ch1loop:
@ref210:
	.byte $8c,$58,$9d,$52,$9d
@ref211:
	.byte $42,$95,$40,$a5
@ref212:
	.byte $58,$9d,$52,$9d
@ref213:
	.byte $42,$95,$40,$a5
@ref214:
	.byte $1a,$bd
@ref215:
	.byte $bf
@ref216:
	.byte $1a,$bd
@ref217:
	.byte $bf
@ref218:
	.byte $82,$4a,$85,$4d,$53,$4b,$55,$53,$4d,$4a,$85,$4d,$53,$4b,$55,$53
	.byte $4c,$81
@ref219:
	.byte $54,$85,$4f,$53,$54,$85,$4f,$53,$4b,$4d,$4b,$4d,$51,$4d,$4b,$4a
	.byte $81
@ref220:
	.byte $4a,$85,$4d,$53,$4b,$55,$53,$4d,$4a,$85,$4d,$53,$4b,$55,$53,$4c
	.byte $81
	.byte $ff,$11
	.word @ref219
@ref222:
	.byte $8c,$1a,$bd
@ref223:
	.byte $bf
@ref224:
	.byte $1a,$bd
@ref225:
	.byte $bf
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@ref226:
	.byte $00,$8d
@ref227:
	.byte $8f
@song4ch2loop:
@ref228:
	.byte $80,$1a,$85,$32,$85,$1a,$85,$33,$2f,$1a,$85,$32,$85,$1a,$85,$33
	.byte $1a,$81
@ref229:
	.byte $24,$85,$3c,$85,$24,$85,$3c,$85,$1a,$85,$32,$85,$1b,$33,$1b,$2e
	.byte $81
@ref230:
	.byte $1a,$85,$32,$85,$1a,$85,$33,$2f,$1a,$85,$32,$85,$1a,$85,$33,$1a
	.byte $81
	.byte $ff,$11
	.word @ref229
@ref232:
	.byte $00,$bd
@ref233:
	.byte $bf
@ref234:
	.byte $00,$bd
@ref235:
	.byte $bf
	.byte $ff,$11
	.word @ref230
@ref237:
	.byte $24,$85,$3c,$85,$24,$85,$3c,$85,$1a,$85,$32,$85,$31,$35,$1b,$2e
	.byte $81
	.byte $ff,$11
	.word @ref230
	.byte $ff,$11
	.word @ref237
@ref240:
	.byte $00,$bd
@ref241:
	.byte $bf
@ref242:
	.byte $00,$bd
@ref243:
	.byte $bf
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@ref244:
	.byte $8f
@ref245:
	.byte $8f
@song4ch3loop:
@ref246:
	.byte $88,$09,$8a,$1a,$1a,$8c,$0b,$8a,$1a,$1a,$88,$08,$8a,$1a,$1a,$1a
	.byte $8c,$0b,$88,$09,$09,$8a,$1a,$1a,$8c,$0b,$8a,$1a,$1a,$88,$08,$8a
	.byte $1a,$1a,$1a,$88,$09,$08,$81
@ref247:
	.byte $09,$8a,$1a,$1a,$8c,$0b,$8a,$1a,$1a,$88,$08,$8a,$1a,$1a,$1a,$8c
	.byte $0b,$88,$09,$09,$8a,$1a,$1a,$8c,$0b,$8a,$1a,$1a,$88,$08,$8a,$1a
	.byte $1a,$1a,$88,$09,$08,$81
	.byte $ff,$19
	.word @ref247
	.byte $ff,$19
	.word @ref247
	.byte $ff,$19
	.word @ref247
	.byte $ff,$19
	.word @ref247
	.byte $ff,$19
	.word @ref247
	.byte $ff,$19
	.word @ref247
	.byte $ff,$19
	.word @ref247
	.byte $ff,$19
	.word @ref247
	.byte $ff,$19
	.word @ref247
	.byte $ff,$19
	.word @ref247
	.byte $ff,$19
	.word @ref247
	.byte $ff,$19
	.word @ref247
	.byte $ff,$19
	.word @ref247
	.byte $ff,$19
	.word @ref247
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@ref262:
	.byte $8f
@ref263:
	.byte $8f
@song4ch4loop:
@ref264:
	.byte $bf
@ref265:
	.byte $bf
@ref266:
	.byte $bf
@ref267:
	.byte $bf
@ref268:
	.byte $bf
@ref269:
	.byte $bf
@ref270:
	.byte $bf
@ref271:
	.byte $bf
@ref272:
	.byte $bf
@ref273:
	.byte $bf
@ref274:
	.byte $bf
@ref275:
	.byte $bf
@ref276:
	.byte $bf
@ref277:
	.byte $bf
@ref278:
	.byte $bf
@ref279:
	.byte $bf
	.byte $fd
	.word @song4ch4loop


@song5ch0:
	.byte $fb,$06
@song5ch0loop:
@ref280:
	.byte $f9,$85
	.byte $fd
	.word @song5ch0loop

@song5ch1:
@song5ch1loop:
@ref281:
	.byte $f9,$85
	.byte $fd
	.word @song5ch1loop

@song5ch2:
@song5ch2loop:
@ref282:
	.byte $84,$4b,$53,$59,$61,$63,$61,$59,$53,$4b,$53,$59,$61,$63,$61,$6b
	.byte $63,$41,$49,$4f,$57,$59,$57,$4f,$49,$41,$49,$4f,$57,$59,$61,$67
	.byte $60,$81
	.byte $fd
	.word @song5ch2loop

@song5ch3:
@song5ch3loop:
@ref283:
	.byte $a8,$20,$99,$21,$20,$9d,$20,$99,$21,$20,$9d
	.byte $fd
	.word @song5ch3loop

@song5ch4:
@song5ch4loop:
@ref284:
	.byte $f9,$85
	.byte $fd
	.word @song5ch4loop


@song6ch0:
	.byte $fb,$10
@song6ch0loop:
@ref285:
	.byte $9c,$58,$83,$4e,$83,$52,$91,$60,$83,$5c,$83,$58,$91
@ref286:
	.byte $4e,$83,$60,$83,$4f,$52,$8d,$58,$83,$4e,$83,$52,$91
@ref287:
	.byte $58,$83,$4e,$83,$52,$91,$60,$83,$5c,$83,$58,$91
	.byte $ff,$0d
	.word @ref286
@ref289:
	.byte $58,$89,$5c,$52,$8f,$62,$89,$60,$5c,$83,$61,$63,$66,$81
@ref290:
	.byte $60,$89,$4e,$52,$8d,$4e,$53,$53,$59,$60,$4e,$8f
	.byte $ff,$0c
	.word @ref287
	.byte $ff,$0d
	.word @ref286
	.byte $ff,$0c
	.word @ref287
	.byte $ff,$0d
	.word @ref286
	.byte $ff,$0e
	.word @ref289
	.byte $ff,$0c
	.word @ref290
@ref297:
	.byte $00,$9d
@ref298:
	.byte $9f
@ref299:
	.byte $a4,$4e,$4e,$4a,$4a,$4e,$52,$54,$52,$4e,$4e,$4a,$4a,$4e,$52,$5c
	.byte $5e
@ref300:
	.byte $4e,$4e,$4a,$4a,$4e,$54,$52,$50,$4e,$4e,$4a,$4a,$4e,$52,$5c,$5e
@ref301:
	.byte $9c,$58,$83,$59,$5e,$5c,$58,$54,$83,$54,$83,$4f,$5e,$83,$5e,$83
	.byte $4f,$5c,$83,$5c,$83,$4e,$81
@ref302:
	.byte $58,$83,$58,$83,$53,$54,$83,$54,$83,$4f,$52,$83,$52,$83,$4d,$4e
	.byte $83,$4e,$83,$46,$40
@ref303:
	.byte $58,$83,$59,$5e,$5c,$58,$54,$83,$54,$83,$4f,$5e,$83,$5e,$83,$4f
	.byte $5c,$83,$5c,$83,$4e,$81
	.byte $ff,$15
	.word @ref302
	.byte $fd
	.word @song6ch0loop

@song6ch1:
@song6ch1loop:
@ref305:
	.byte $00,$bd
@ref306:
	.byte $bf
@ref307:
	.byte $00,$bd
@ref308:
	.byte $bf
@ref309:
	.byte $9c,$66,$89,$6a,$60,$8f,$6a,$89,$66,$66,$8f
@ref310:
	.byte $66,$89,$4e,$60,$8d,$5c,$5d,$61,$63,$66,$5c,$8f
@ref311:
	.byte $00,$bd
@ref312:
	.byte $bf
@ref313:
	.byte $00,$bd
@ref314:
	.byte $bf
@ref315:
	.byte $66,$89,$6a,$60,$8f,$6a,$89,$66,$66,$8f
	.byte $ff,$0c
	.word @ref310
@ref317:
	.byte $9e,$4f,$4e,$4e,$83,$37,$4f,$4e,$4e,$83,$36,$81
@ref318:
	.byte $a0,$4f,$4e,$4e,$83,$37,$9e,$4f,$4e,$4e,$83,$36,$81
@ref319:
	.byte $4f,$4e,$4e,$83,$37,$4f,$4e,$4e,$83,$36,$81
	.byte $ff,$0b
	.word @ref318
@ref321:
	.byte $9a,$51,$50,$51,$38,$51,$9e,$4f,$4e,$4f,$36,$4f,$9a,$47,$46,$47
	.byte $5e,$47,$4f,$4e,$4f,$36,$4e,$81
@ref322:
	.byte $9e,$59,$58,$59,$40,$59,$4f,$4e,$4f,$36,$4f,$9a,$45,$44,$45,$5c
	.byte $45,$9e,$4f,$36,$4f,$36,$4e,$36
	.byte $ff,$15
	.word @ref321
	.byte $ff,$15
	.word @ref322
	.byte $fd
	.word @song6ch1loop

@song6ch2:
@song6ch2loop:
@ref325:
	.byte $84,$28,$83,$40,$83,$22,$85,$3a,$22,$3a,$85,$28,$83,$40,$83,$22
	.byte $85,$3a,$22,$3a,$85
@ref326:
	.byte $28,$83,$40,$83,$22,$85,$3a,$22,$3a,$85,$28,$83,$40,$83,$22,$85
	.byte $3a,$40,$3a,$85
@ref327:
	.byte $28,$83,$40,$83,$22,$85,$3a,$22,$3a,$85,$28,$83,$40,$83,$22,$85
	.byte $3a,$22,$3a,$85
	.byte $ff,$14
	.word @ref326
@ref329:
	.byte $29,$31,$37,$40,$3a,$83,$37,$31,$29,$2d,$33,$3b,$44,$3e,$83,$37
	.byte $49,$44,$81
	.byte $ff,$13
	.word @ref329
	.byte $ff,$14
	.word @ref327
	.byte $ff,$14
	.word @ref326
	.byte $ff,$14
	.word @ref327
	.byte $ff,$14
	.word @ref326
	.byte $ff,$13
	.word @ref329
	.byte $ff,$13
	.word @ref329
@ref337:
	.byte $36,$89,$3d,$36,$89,$3c,$81
@ref338:
	.byte $46,$89,$3d,$36,$89,$32,$81
	.byte $ff,$07
	.word @ref337
	.byte $ff,$07
	.word @ref338
@ref341:
	.byte $38,$89,$28,$2e,$36,$89,$24,$2c,$2e,$89,$24,$2e,$36,$8d
@ref342:
	.byte $28,$83,$1e,$28,$1e,$2e,$28,$24,$83,$1e,$24,$1e,$2c,$24,$22,$83
	.byte $2c,$34,$2c,$22,$1c,$1e,$83,$2d,$1e,$83
	.byte $ff,$0e
	.word @ref341
	.byte $ff,$1a
	.word @ref342
	.byte $fd
	.word @song6ch2loop

@song6ch3:
@song6ch3loop:
@ref345:
	.byte $a8,$1b,$08,$1a,$83,$09,$1b,$08,$1a,$83,$09,$1b,$08,$1a,$83,$09
	.byte $1b,$08,$1b,$08,$08,$81
@ref346:
	.byte $1b,$08,$1a,$83,$09,$1b,$08,$1a,$83,$09,$1b,$08,$1a,$83,$09,$1b
	.byte $08,$1b,$08,$08,$08
@ref347:
	.byte $1b,$08,$1a,$83,$09,$1b,$08,$1a,$83,$09,$1b,$08,$1a,$83,$09,$1b
	.byte $08,$1b,$08,$08,$81
	.byte $ff,$15
	.word @ref346
	.byte $ff,$15
	.word @ref347
	.byte $ff,$15
	.word @ref346
	.byte $ff,$15
	.word @ref347
	.byte $ff,$15
	.word @ref346
	.byte $ff,$15
	.word @ref347
	.byte $ff,$15
	.word @ref346
	.byte $ff,$15
	.word @ref347
	.byte $ff,$15
	.word @ref346
@ref357:
	.byte $1b,$08,$1a,$83,$09,$1b,$08,$1a,$83,$08,$81
@ref358:
	.byte $1b,$08,$1a,$83,$09,$1b,$08,$1b,$08,$08,$81
	.byte $ff,$0b
	.word @ref357
	.byte $ff,$0b
	.word @ref358
	.byte $ff,$15
	.word @ref347
	.byte $ff,$15
	.word @ref346
	.byte $ff,$15
	.word @ref347
	.byte $ff,$15
	.word @ref346
	.byte $fd
	.word @song6ch3loop

@song6ch4:
@song6ch4loop:
@ref365:
	.byte $bf
@ref366:
	.byte $bf
@ref367:
	.byte $bf
@ref368:
	.byte $bf
@ref369:
	.byte $bf
@ref370:
	.byte $bf
@ref371:
	.byte $bf
@ref372:
	.byte $bf
@ref373:
	.byte $bf
@ref374:
	.byte $bf
@ref375:
	.byte $bf
@ref376:
	.byte $bf
@ref377:
	.byte $9f
@ref378:
	.byte $9f
@ref379:
	.byte $9f
@ref380:
	.byte $9f
@ref381:
	.byte $bf
@ref382:
	.byte $bf
@ref383:
	.byte $bf
@ref384:
	.byte $bf
	.byte $fd
	.word @song6ch4loop


@song7ch0:
	.byte $fb,$0a
@song7ch0loop:
@ref385:
	.byte $00,$f9,$83
@ref386:
	.byte $00,$f9,$83
@ref387:
	.byte $a2,$4b,$55,$55,$55,$4f,$47,$47,$01,$45,$4b,$45,$3d,$40,$44,$40
	.byte $3c,$41,$01,$4b,$55,$55,$55,$4f,$47,$47,$01,$44,$4a,$44,$3c,$41
	.byte $41,$3c,$85,$00,$85
@ref388:
	.byte $4b,$55,$55,$55,$4f,$47,$47,$01,$45,$4b,$45,$3d,$40,$44,$40,$3c
	.byte $41,$01,$4b,$55,$55,$55,$4f,$47,$47,$01,$44,$4a,$44,$3c,$41,$41
	.byte $3c,$85,$00,$85
@ref389:
	.byte $00,$f9,$83
	.byte $ff,$24
	.word @ref388
	.byte $ff,$24
	.word @ref388
@ref392:
	.byte $55,$55,$4f,$4f,$55,$55,$4f,$01,$53,$53,$4b,$4b,$53,$53,$4b,$01
	.byte $55,$55,$4f,$4f,$55,$55,$4e,$83,$4e,$53,$4e,$4a,$4f,$4a,$48,$4a
	.byte $85,$33,$00,$81
@ref393:
	.byte $bf
	.byte $ff,$24
	.word @ref388
	.byte $ff,$24
	.word @ref388
	.byte $fd
	.word @song7ch0loop

@song7ch1:
@song7ch1loop:
@ref396:
	.byte $00,$f9,$83
@ref397:
	.byte $a4,$3c,$85,$44,$85,$46,$85,$4e,$85,$4a,$85,$44,$85,$41,$3d,$3b
	.byte $41,$3c,$85,$44,$85,$46,$85,$4e,$85,$4b,$3d,$41,$33,$3c,$8d
@ref398:
	.byte $00,$f9,$83
@ref399:
	.byte $3c,$85,$44,$85,$46,$85,$4e,$85,$4a,$85,$44,$85,$41,$3d,$3b,$41
	.byte $3c,$85,$44,$85,$46,$85,$4e,$85,$4b,$3d,$41,$33,$3c,$8d
@ref400:
	.byte $00,$f9,$83
	.byte $ff,$1e
	.word @ref399
	.byte $ff,$1e
	.word @ref399
@ref403:
	.byte $3d,$37,$44,$85,$3d,$37,$44,$85,$3b,$33,$40,$85,$3b,$33,$46,$85
	.byte $3d,$37,$45,$4b,$3d,$37,$45,$4b,$33,$3b,$41,$49,$4a,$85,$00,$85
@ref404:
	.byte $b9,$32,$36,$3a
	.byte $ff,$1e
	.word @ref399
	.byte $ff,$1e
	.word @ref399
	.byte $fd
	.word @song7ch1loop

@song7ch2:
@song7ch2loop:
@ref407:
	.byte $84,$25,$01,$32,$85,$2f,$01,$24,$85,$2c,$00,$24,$00,$32,$85,$29
	.byte $1b,$1f,$22,$00,$25,$01,$32,$85,$2f,$01,$24,$85,$24,$00,$1a,$00
	.byte $22,$00,$1a,$00,$24,$85,$1a,$85
@ref408:
	.byte $25,$01,$32,$85,$2f,$01,$24,$85,$2c,$00,$24,$00,$32,$85,$29,$1b
	.byte $1f,$22,$00,$25,$01,$32,$85,$2f,$01,$24,$85,$24,$00,$1a,$00,$22
	.byte $00,$1a,$00,$24,$85,$1a,$85
	.byte $ff,$27
	.word @ref408
	.byte $ff,$27
	.word @ref408
	.byte $ff,$27
	.word @ref408
	.byte $ff,$27
	.word @ref408
	.byte $ff,$27
	.word @ref408
@ref414:
	.byte $a2,$1f,$01,$25,$01,$1f,$01,$25,$01,$23,$01,$29,$01,$23,$01,$1b
	.byte $01,$1f,$01,$25,$01,$1f,$01,$25,$01,$28,$85,$22,$85,$1a,$89,$a4
	.byte $1a,$81
@ref415:
	.byte $32,$89,$1b,$32,$8d,$00,$9d
	.byte $ff,$27
	.word @ref407
	.byte $ff,$27
	.word @ref408
	.byte $fd
	.word @song7ch2loop

@song7ch3:
@song7ch3loop:
@ref418:
	.byte $a6,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e
	.byte $85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e
	.byte $85
@ref419:
	.byte $1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85
	.byte $1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85,$1e,$85
@ref420:
	.byte $02,$85,$12,$85,$02,$85,$13,$03,$02,$85,$12,$85,$03,$13,$03,$03
	.byte $02,$85,$12,$85,$02,$85,$13,$03,$03,$13,$03,$13,$02,$85,$12,$85
	.byte $ff,$20
	.word @ref420
	.byte $ff,$20
	.word @ref419
	.byte $ff,$20
	.word @ref420
	.byte $ff,$20
	.word @ref420
	.byte $ff,$20
	.word @ref420
	.byte $ff,$10
	.word @ref419
	.byte $ff,$20
	.word @ref420
	.byte $ff,$20
	.word @ref420
	.byte $fd
	.word @song7ch3loop

@song7ch4:
@song7ch4loop:
@ref429:
	.byte $f9,$85
@ref430:
	.byte $f9,$85
@ref431:
	.byte $f9,$85
@ref432:
	.byte $f9,$85
@ref433:
	.byte $f9,$85
@ref434:
	.byte $f9,$85
@ref435:
	.byte $f9,$85
@ref436:
	.byte $f9,$85
@ref437:
	.byte $bf
@ref438:
	.byte $f9,$85
@ref439:
	.byte $f9,$85
	.byte $fd
	.word @song7ch4loop


@song8ch0:
	.byte $fb,$0e
@ref440:
	.byte $b0,$32,$36,$3a,$45,$40,$40,$3c,$32,$36,$38,$43,$40,$40,$38,$30
	.byte $32,$36,$3d,$38,$38,$36,$32,$85,$4a,$4a,$4a,$81
@song8ch0loop:
@ref441:
	.byte $b4,$32,$36,$3a,$45,$40,$40,$3c,$32,$36,$38,$43,$40,$40,$38,$30
	.byte $32,$36,$3d,$38,$38,$36,$32,$85,$4a,$4a,$4a,$81
@ref442:
	.byte $32,$36,$3a,$45,$40,$40,$3c,$32,$36,$38,$43,$40,$40,$38,$30,$32
	.byte $36,$3d,$38,$38,$36,$32,$85,$4a,$4a,$4a,$81
@ref443:
	.byte $00,$bd
@ref444:
	.byte $b2,$32,$8d,$32,$8d,$32,$8d,$32,$8d
@ref445:
	.byte $b4,$4a,$4a,$00,$4a,$50,$4a,$00,$4a,$40,$42,$48,$4a,$48,$42,$40
	.byte $3c,$40,$40,$00,$32,$40,$40,$00,$40,$3c,$40,$3c,$38,$36,$38,$36
	.byte $32
@ref446:
	.byte $4a,$4a,$00,$4a,$50,$4a,$00,$4a,$40,$42,$48,$4a,$48,$42,$40,$3c
	.byte $40,$40,$00,$32,$40,$40,$00,$40,$3c,$40,$3c,$38,$36,$38,$36,$32
@ref447:
	.byte $4a,$4a,$00,$4a,$50,$4a,$00,$4a,$40,$42,$48,$4a,$48,$42,$40,$3c
	.byte $40,$40,$40,$40,$42,$48,$4a,$4e,$50,$54,$58,$54,$4a,$00,$54,$54
@ref448:
	.byte $50,$50,$00,$50,$54,$50,$00,$50,$4e,$50,$4e,$4a,$48,$42,$40,$3c
	.byte $40,$40,$00,$32,$40,$40,$00,$40,$3c,$40,$3c,$38,$36,$38,$36,$30
@ref449:
	.byte $b2,$38,$38,$00,$38,$38,$38,$00,$38,$36,$36,$00,$36,$36,$36,$00
	.byte $36,$32,$32,$00,$40,$32,$32,$01,$b4,$40,$42,$48,$4a,$48,$42,$40
	.byte $3c
	.byte $ff,$1b
	.word @ref440
	.byte $ff,$1b
	.word @ref442
@ref452:
	.byte $32,$38,$40,$4b,$68,$62,$5a,$58,$50,$4a,$40,$00,$40,$3e,$40,$3c
	.byte $42,$48,$4a,$50,$4a,$48,$42,$40,$42,$40,$42,$40,$42,$48,$42
@ref453:
	.byte $32,$38,$40,$4b,$68,$62,$5a,$58,$50,$4a,$40,$00,$40,$3e,$40,$3c
	.byte $42,$48,$4a,$50,$58,$62,$68,$58,$5a,$58,$5a,$58,$54,$50,$4e
	.byte $ff,$20
	.word @ref445
	.byte $ff,$20
	.word @ref446
	.byte $ff,$20
	.word @ref447
	.byte $ff,$20
	.word @ref448
	.byte $ff,$1f
	.word @ref449
	.byte $fd
	.word @song8ch0loop

@song8ch1:
@ref459:
	.byte $00,$b9,$b0,$62,$81
@song8ch1loop:
@ref460:
	.byte $ac,$52,$54,$52,$5d,$58,$58,$54,$4a,$4e,$50,$5b,$58,$58,$5a,$4e
	.byte $50,$4e,$55,$50,$50,$4e,$4a,$85,$62,$62,$62,$58
@ref461:
	.byte $52,$54,$52,$5d,$58,$58,$54,$4a,$4e,$50,$5b,$58,$58,$5a,$4e,$50
	.byte $4e,$55,$50,$50,$4e,$4a,$85,$62,$62,$62,$58
@ref462:
	.byte $00,$bd
@ref463:
	.byte $b2,$38,$8d,$48,$8d,$40,$8d,$3c,$8d
@ref464:
	.byte $38,$8d,$48,$8d,$40,$8d,$3c,$8d
	.byte $ff,$08
	.word @ref464
	.byte $ff,$08
	.word @ref464
	.byte $ff,$08
	.word @ref464
@ref468:
	.byte $32,$8d,$30,$8d,$32,$8b,$00,$8f
	.byte $ff,$1b
	.word @ref460
	.byte $ff,$1b
	.word @ref461
@ref471:
	.byte $b2,$32,$8d,$38,$8d,$36,$8d,$32,$8d
@ref472:
	.byte $32,$8d,$38,$8d,$36,$8d,$32,$85,$40,$3c,$38,$36
	.byte $ff,$08
	.word @ref464
	.byte $ff,$08
	.word @ref464
	.byte $ff,$08
	.word @ref464
	.byte $ff,$08
	.word @ref464
	.byte $ff,$08
	.word @ref468
	.byte $fd
	.word @song8ch1loop

@song8ch2:
@ref478:
	.byte $00,$bd
@song8ch2loop:
@ref479:
	.byte $ac,$1a,$1a,$28,$1a,$00,$28,$22,$1a,$1a,$1a,$20,$1a,$00,$20,$28
	.byte $20,$18,$18,$1e,$18,$00,$20,$18,$1e,$1a,$00,$83,$1a,$00,$1a,$00
@ref480:
	.byte $1a,$1a,$28,$1a,$00,$28,$22,$1a,$1a,$1a,$20,$1a,$00,$20,$28,$20
	.byte $18,$18,$1e,$18,$00,$20,$18,$1e,$1a,$00,$83,$1a,$00,$1a,$00
@ref481:
	.byte $1a,$85,$aa,$18,$1a,$20,$1e,$ac,$1a,$85,$aa,$28,$24,$20,$1e,$ac
	.byte $1a,$85,$aa,$18,$1a,$20,$28,$ac,$24,$85,$aa,$24,$20,$1e,$1a
@ref482:
	.byte $ac,$1a,$85,$aa,$18,$1a,$20,$1e,$ac,$1a,$85,$aa,$28,$24,$20,$1e
	.byte $ac,$1a,$85,$aa,$18,$1a,$20,$28,$ac,$24,$85,$aa,$24,$20,$1e,$1a
	.byte $ff,$18
	.word @ref482
	.byte $ff,$18
	.word @ref482
	.byte $ff,$18
	.word @ref482
	.byte $ff,$18
	.word @ref482
@ref487:
	.byte $1a,$1a,$1a,$1a,$1a,$1a,$1a,$1a,$1e,$1e,$1e,$1e,$1e,$1e,$1e,$1e
	.byte $20,$20,$20,$20,$1a,$1a,$1a,$1a,$28,$2a,$30,$32,$30,$2a,$28,$00
	.byte $ff,$1f
	.word @ref479
	.byte $ff,$1f
	.word @ref480
@ref490:
	.byte $aa,$1a,$1a,$10,$1a,$00,$20,$20,$20,$1a,$1a,$10,$1a,$00,$1a,$1a
	.byte $1a,$28,$28,$1e,$28,$00,$1e,$1e,$1e,$1a,$1a,$1a,$1a,$1a,$28,$30
	.byte $28
@ref491:
	.byte $1a,$1a,$10,$1a,$00,$20,$20,$20,$1a,$1a,$10,$1a,$00,$1a,$1a,$1a
	.byte $28,$28,$1e,$28,$00,$1e,$1e,$1e,$1a,$1a,$1a,$1a,$b2,$28,$24,$20
	.byte $1e
	.byte $ff,$18
	.word @ref482
	.byte $ff,$18
	.word @ref482
	.byte $ff,$18
	.word @ref482
	.byte $ff,$18
	.word @ref482
	.byte $ff,$20
	.word @ref487
	.byte $fd
	.word @song8ch2loop

@song8ch3:
@ref497:
	.byte $00,$bd
@song8ch3loop:
@ref498:
	.byte $aa,$02,$ae,$1e,$aa,$10,$03,$ae,$1e,$aa,$10,$ae,$1e,$aa,$02,$ae
	.byte $1e,$aa,$10,$03,$ae,$1e,$aa,$10,$ae,$1e,$aa,$02,$ae,$1e,$aa,$10
	.byte $03,$ae,$1e,$aa,$10,$ae,$1e,$aa,$02,$ae,$1e,$aa,$10,$ae,$1e,$aa
	.byte $02,$02,$10,$ae,$1e
	.byte $ff,$1d
	.word @ref498
@ref500:
	.byte $aa,$02,$02,$10,$ae,$1e,$aa,$02,$02,$10,$ae,$1e,$aa,$02,$02,$10
	.byte $ae,$1e,$aa,$02,$ae,$1e,$aa,$10,$ae,$1e,$aa,$02,$02,$10,$ae,$1e
	.byte $aa,$02,$02,$10,$ae,$1e,$aa,$02,$02,$10,$ae,$1e,$aa,$02,$ae,$1e
	.byte $aa,$10,$ae,$1e
	.byte $ff,$20
	.word @ref500
	.byte $ff,$20
	.word @ref500
	.byte $ff,$20
	.word @ref500
	.byte $ff,$20
	.word @ref500
	.byte $ff,$20
	.word @ref500
@ref506:
	.byte $aa,$02,$02,$10,$ae,$1e,$aa,$02,$02,$10,$ae,$1e,$aa,$02,$02,$10
	.byte $ae,$1e,$aa,$02,$ae,$1e,$aa,$10,$ae,$1e,$aa,$02,$02,$10,$ae,$1e
	.byte $aa,$02,$02,$10,$ae,$1e,$aa,$02,$8d
@ref507:
	.byte $02,$ae,$1e,$aa,$10,$03,$ae,$1e,$aa,$10,$ae,$1e,$aa,$02,$ae,$1e
	.byte $aa,$10,$03,$ae,$1e,$aa,$10,$ae,$1e,$aa,$02,$ae,$1e,$aa,$10,$03
	.byte $ae,$1e,$aa,$10,$ae,$1e,$aa,$02,$ae,$1e,$aa,$10,$ae,$1e,$aa,$02
	.byte $02,$10,$ae,$1e
	.byte $ff,$1d
	.word @ref498
	.byte $ff,$20
	.word @ref500
	.byte $ff,$20
	.word @ref500
	.byte $ff,$20
	.word @ref500
	.byte $ff,$20
	.word @ref500
	.byte $ff,$20
	.word @ref500
	.byte $ff,$20
	.word @ref500
	.byte $ff,$1a
	.word @ref506
	.byte $fd
	.word @song8ch3loop

@song8ch4:
@ref516:
	.byte $bf
@song8ch4loop:
@ref517:
	.byte $bf
@ref518:
	.byte $bf
@ref519:
	.byte $bf
@ref520:
	.byte $bf
@ref521:
	.byte $bf
@ref522:
	.byte $bf
@ref523:
	.byte $bf
@ref524:
	.byte $bf
@ref525:
	.byte $bf
@ref526:
	.byte $bf
@ref527:
	.byte $bf
@ref528:
	.byte $bf
@ref529:
	.byte $bf
@ref530:
	.byte $bf
@ref531:
	.byte $bf
@ref532:
	.byte $bf
@ref533:
	.byte $bf
@ref534:
	.byte $bf
	.byte $fd
	.word @song8ch4loop
