// CHR-ROM Map & decos indexes
// Generated by rle44mapchrrom.exe v0.1 20171113
// Copyleft 2017 by The Mojon Twins

// Map # 0 read from level0.map (4x6)

// Definitions

#define MAP_00_CHRROM    1
#define MAP_00_BASE      0x0000
#define MAP_00_W         4
#define MAP_00_H         6
#define MAP_00_MAXPANTS  24

// Screens index

const unsigned int map_00_scr_offsets [] = {
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x0059, 
	MAP_00_BASE + 0x00C3, MAP_00_BASE + 0x011D, 
	MAP_00_BASE + 0x0170, MAP_00_BASE + 0x01D9, 
	MAP_00_BASE + 0x0227, MAP_00_BASE + 0x0281, 
	MAP_00_BASE + 0x02C4, MAP_00_BASE + 0x032F, 
	MAP_00_BASE + 0x0394, MAP_00_BASE + 0x03F1, 
	MAP_00_BASE + 0x045B, MAP_00_BASE + 0x04B4, 
	MAP_00_BASE + 0x04FD, MAP_00_BASE + 0x0551, 
	MAP_00_BASE + 0x05A5, MAP_00_BASE + 0x0607, 
	MAP_00_BASE + 0x0666, MAP_00_BASE + 0x06D1, 
	MAP_00_BASE + 0x0718, MAP_00_BASE + 0x0762, 
	MAP_00_BASE + 0x07AE, MAP_00_BASE + 0x0810
};

// Total screens size in bytes is 2149

// Locks
// These tiles are locks:  15
const unsigned char map_00_locks [] = {
	0x00, 0xa7, 0x16, 0x96
};

// Map # 1 read from level1.map (4x6)

// Definitions

#define MAP_01_CHRROM    1
#define MAP_01_BASE      0x0865
#define MAP_01_W         4
#define MAP_01_H         6
#define MAP_01_MAXPANTS  24

// Screens index

const unsigned int map_01_scr_offsets [] = {
	MAP_01_BASE + 0x0000, MAP_01_BASE + 0x0048, 
	MAP_01_BASE + 0x00A6, MAP_01_BASE + 0x0105, 
	MAP_01_BASE + 0x0155, MAP_01_BASE + 0x01A8, 
	MAP_01_BASE + 0x01F3, MAP_01_BASE + 0x0212, 
	MAP_01_BASE + 0x0246, MAP_01_BASE + 0x02B3, 
	MAP_01_BASE + 0x0316, MAP_01_BASE + 0x0363, 
	MAP_01_BASE + 0x03BD, MAP_01_BASE + 0x0415, 
	MAP_01_BASE + 0x0475, MAP_01_BASE + 0x04C0, 
	MAP_01_BASE + 0x0519, MAP_01_BASE + 0x057D, 
	MAP_01_BASE + 0x05B9, MAP_01_BASE + 0x05F4, 
	MAP_01_BASE + 0x0647, MAP_01_BASE + 0x0685, 
	MAP_01_BASE + 0x06C7, MAP_01_BASE + 0x0710
};

// Total screens size in bytes is 1887

// Locks
// These tiles are locks:  15
const unsigned char map_01_locks [] = {
	0x10, 0x59
};

// Map # 2 read from level2.map (4x6)

// Definitions

#define MAP_02_CHRROM    1
#define MAP_02_BASE      0x0FC4
#define MAP_02_W         4
#define MAP_02_H         6
#define MAP_02_MAXPANTS  24

// Screens index

const unsigned int map_02_scr_offsets [] = {
	MAP_02_BASE + 0x0000, MAP_02_BASE + 0x0071, 
	MAP_02_BASE + 0x00BA, MAP_02_BASE + 0x0110, 
	MAP_02_BASE + 0x0189, MAP_02_BASE + 0x01E6, 
	MAP_02_BASE + 0x024C, MAP_02_BASE + 0x02AD, 
	MAP_02_BASE + 0x02F7, MAP_02_BASE + 0x035D, 
	MAP_02_BASE + 0x03C5, MAP_02_BASE + 0x0439, 
	MAP_02_BASE + 0x04A0, MAP_02_BASE + 0x0508, 
	MAP_02_BASE + 0x055E, MAP_02_BASE + 0x05D5, 
	MAP_02_BASE + 0x0641, MAP_02_BASE + 0x068D, 
	MAP_02_BASE + 0x06E2, MAP_02_BASE + 0x071B, 
	MAP_02_BASE + 0x078D, MAP_02_BASE + 0x0809, 
	MAP_02_BASE + 0x0867, MAP_02_BASE + 0x08D9
};

// Total screens size in bytes is 2382

// Locks
// These tiles are locks:  15
const unsigned char map_02_locks [] = {
	0x03, 0x84, 0x16, 0x91
};

// Map # 3 read from level3.map (12x2)

// Definitions

#define MAP_03_CHRROM    1
#define MAP_03_BASE      0x1912
#define MAP_03_W         12
#define MAP_03_H         2
#define MAP_03_MAXPANTS  24

// Screens index

const unsigned int map_03_scr_offsets [] = {
	0                   , 0                   , 
	MAP_03_BASE + 0x0000, MAP_03_BASE + 0x0014, 
	MAP_03_BASE + 0x002F, MAP_03_BASE + 0x0061, 
	MAP_03_BASE + 0x0075, MAP_03_BASE + 0x00A0, 
	MAP_03_BASE + 0x00E8, MAP_03_BASE + 0x0146, 
	MAP_03_BASE + 0x0170, MAP_03_BASE + 0x0189, 
	MAP_03_BASE + 0x01B4, MAP_03_BASE + 0x01DA, 
	MAP_03_BASE + 0x01F9, MAP_03_BASE + 0x0246, 
	MAP_03_BASE + 0x028F, MAP_03_BASE + 0x02D2, 
	MAP_03_BASE + 0x031D, MAP_03_BASE + 0x0359, 
	MAP_03_BASE + 0x0385, MAP_03_BASE + 0x03A0, 
	MAP_03_BASE + 0x03EA, MAP_03_BASE + 0x0441
};

// Total screens size in bytes is 1129

// Locks
// These tiles are locks:  15
const unsigned char map_03_locks [] = {
	0x09, 0x63, 0x06, 0x7c, 0x0e, 0x54, 0x15, 0x94
};

// Map # 4 read from level4.map (3x4)

// Definitions

#define MAP_04_CHRROM    2
#define MAP_04_BASE      0x0000
#define MAP_04_W         3
#define MAP_04_H         4
#define MAP_04_MAXPANTS  12

// Screens index

const unsigned int map_04_scr_offsets [] = {
	MAP_04_BASE + 0x0000, MAP_04_BASE + 0x0038, 
	MAP_04_BASE + 0x007B, MAP_04_BASE + 0x00CD, 
	MAP_04_BASE + 0x012B, MAP_04_BASE + 0x0186, 
	MAP_04_BASE + 0x01E1, MAP_04_BASE + 0x022B, 
	MAP_04_BASE + 0x029C, MAP_04_BASE + 0x02F8, 
	MAP_04_BASE + 0x0342, MAP_04_BASE + 0x0398
};

// Total screens size in bytes is 1009

// Map # 5 read from level5.map (6x4)

// Definitions

#define MAP_05_CHRROM    2
#define MAP_05_BASE      0x03F1
#define MAP_05_W         6
#define MAP_05_H         4
#define MAP_05_MAXPANTS  24

// Screens index

const unsigned int map_05_scr_offsets [] = {
	MAP_05_BASE + 0x0000, MAP_05_BASE + 0x0057, 
	MAP_05_BASE + 0x0090, MAP_05_BASE + 0x00C6, 
	MAP_05_BASE + 0x0100, MAP_05_BASE + 0x0127, 
	MAP_05_BASE + 0x0199, MAP_05_BASE + 0x01D8, 
	MAP_05_BASE + 0x0221, MAP_05_BASE + 0x0262, 
	MAP_05_BASE + 0x02B7, MAP_05_BASE + 0x02FB, 
	MAP_05_BASE + 0x0357, MAP_05_BASE + 0x03BA, 
	MAP_05_BASE + 0x0404, MAP_05_BASE + 0x0458, 
	MAP_05_BASE + 0x04B9, MAP_05_BASE + 0x0500, 
	MAP_05_BASE + 0x0574, MAP_05_BASE + 0x05C7, 
	MAP_05_BASE + 0x0620, MAP_05_BASE + 0x0672, 
	MAP_05_BASE + 0x06A3, MAP_05_BASE + 0x0705
};

// Total screens size in bytes is 1876

// Locks
// These tiles are locks:  15
const unsigned char map_05_locks [] = {
	0x0d, 0x76, 0x0e, 0x8d, 0x0f, 0x8f
};

// Map # 6 read from level6.map (6x4)

// Definitions

#define MAP_06_CHRROM    2
#define MAP_06_BASE      0x0B45
#define MAP_06_W         6
#define MAP_06_H         4
#define MAP_06_MAXPANTS  24

// Screens index

const unsigned int map_06_scr_offsets [] = {
	MAP_06_BASE + 0x0000, MAP_06_BASE + 0x0087, 
	MAP_06_BASE + 0x00F6, MAP_06_BASE + 0x0147, 
	MAP_06_BASE + 0x01B9, MAP_06_BASE + 0x021F, 
	MAP_06_BASE + 0x0288, MAP_06_BASE + 0x02DD, 
	MAP_06_BASE + 0x032C, MAP_06_BASE + 0x0395, 
	MAP_06_BASE + 0x0416, MAP_06_BASE + 0x048B, 
	MAP_06_BASE + 0x04F2, MAP_06_BASE + 0x0558, 
	MAP_06_BASE + 0x05B9, MAP_06_BASE + 0x062D, 
	MAP_06_BASE + 0x06AF, MAP_06_BASE + 0x0715, 
	MAP_06_BASE + 0x0777, MAP_06_BASE + 0x07D1, 
	MAP_06_BASE + 0x0837, MAP_06_BASE + 0x0894, 
	MAP_06_BASE + 0x08DF, MAP_06_BASE + 0x0939
};

// Total screens size in bytes is 2429

// Locks
// These tiles are locks:  15
const unsigned char map_06_locks [] = {
	0x05, 0xa4, 0x09, 0x2f, 0x0a, 0xa5
};

