// CHR-ROM Map & decos indexes
// Generated by rle44mapchrrom.exe v0.1 20171113
// Copyleft 2017 by The Mojon Twins

// Map # 0 read from level0.map (4x6)

// Definitions

#define MAP_00_CHRROM    1
#define MAP_00_BASE      0x0000
#define MAP_00_W         4
#define MAP_00_H         6
#define MAP_00_MAXPANTS  24

// Screens index

const unsigned int map_00_scr_offsets [] = {
	MAP_00_BASE + 0x0000, MAP_00_BASE + 0x005C, 
	MAP_00_BASE + 0x00C9, MAP_00_BASE + 0x0123, 
	MAP_00_BASE + 0x0175, MAP_00_BASE + 0x01E0, 
	MAP_00_BASE + 0x0234, MAP_00_BASE + 0x0299, 
	MAP_00_BASE + 0x02DD, MAP_00_BASE + 0x0348, 
	MAP_00_BASE + 0x03B5, MAP_00_BASE + 0x0412, 
	MAP_00_BASE + 0x047C, MAP_00_BASE + 0x04D6, 
	MAP_00_BASE + 0x0522, MAP_00_BASE + 0x057C, 
	MAP_00_BASE + 0x05C9, MAP_00_BASE + 0x062F, 
	MAP_00_BASE + 0x0696, MAP_00_BASE + 0x0700, 
	MAP_00_BASE + 0x0747, MAP_00_BASE + 0x0795, 
	MAP_00_BASE + 0x07E3, MAP_00_BASE + 0x0846
};

// Total screens size in bytes is 2203

// Locks
// These tiles are locks:  15
const unsigned char map_00_locks [] = {
	0x00, 0xa7, 0x16, 0x96
};

// Map # 1 read from level1.map (4x6)

// Definitions

#define MAP_01_CHRROM    1
#define MAP_01_BASE      0x089B
#define MAP_01_W         4
#define MAP_01_H         6
#define MAP_01_MAXPANTS  24

// Screens index

const unsigned int map_01_scr_offsets [] = {
	MAP_01_BASE + 0x0000, MAP_01_BASE + 0x0048, 
	MAP_01_BASE + 0x00A6, MAP_01_BASE + 0x0105, 
	MAP_01_BASE + 0x0155, MAP_01_BASE + 0x01A8, 
	MAP_01_BASE + 0x01F3, MAP_01_BASE + 0x0212, 
	MAP_01_BASE + 0x0246, MAP_01_BASE + 0x02B3, 
	MAP_01_BASE + 0x0316, MAP_01_BASE + 0x0363, 
	MAP_01_BASE + 0x03BD, MAP_01_BASE + 0x0415, 
	MAP_01_BASE + 0x0475, MAP_01_BASE + 0x04C0, 
	MAP_01_BASE + 0x0519, MAP_01_BASE + 0x057D, 
	MAP_01_BASE + 0x05B9, MAP_01_BASE + 0x05F4, 
	MAP_01_BASE + 0x0647, MAP_01_BASE + 0x0685, 
	MAP_01_BASE + 0x06C7, MAP_01_BASE + 0x0710
};

// Total screens size in bytes is 1887

// Locks
// These tiles are locks:  15
const unsigned char map_01_locks [] = {
	0x10, 0x59
};

// Map # 2 read from level2.map (4x6)

// Definitions

#define MAP_02_CHRROM    1
#define MAP_02_BASE      0x0FFA
#define MAP_02_W         4
#define MAP_02_H         6
#define MAP_02_MAXPANTS  24

// Screens index

const unsigned int map_02_scr_offsets [] = {
	MAP_02_BASE + 0x0000, MAP_02_BASE + 0x0071, 
	MAP_02_BASE + 0x00BA, MAP_02_BASE + 0x0110, 
	MAP_02_BASE + 0x0189, MAP_02_BASE + 0x01E6, 
	MAP_02_BASE + 0x024C, MAP_02_BASE + 0x02AD, 
	MAP_02_BASE + 0x02F7, MAP_02_BASE + 0x035D, 
	MAP_02_BASE + 0x03C5, MAP_02_BASE + 0x0439, 
	MAP_02_BASE + 0x04A0, MAP_02_BASE + 0x0508, 
	MAP_02_BASE + 0x055E, MAP_02_BASE + 0x05D5, 
	MAP_02_BASE + 0x0641, MAP_02_BASE + 0x068D, 
	MAP_02_BASE + 0x06E2, MAP_02_BASE + 0x0718, 
	MAP_02_BASE + 0x078A, MAP_02_BASE + 0x0809, 
	MAP_02_BASE + 0x0865, MAP_02_BASE + 0x08D7
};

// Total screens size in bytes is 2380

// Locks
// These tiles are locks:  15
const unsigned char map_02_locks [] = {
	0x03, 0x84, 0x16, 0x91
};

// Map # 3 read from level3.map (12x2)

// Definitions

#define MAP_03_CHRROM    1
#define MAP_03_BASE      0x1946
#define MAP_03_W         12
#define MAP_03_H         2
#define MAP_03_MAXPANTS  24

// Screens index

const unsigned int map_03_scr_offsets [] = {
	MAP_03_BASE + 0x0000, MAP_03_BASE + 0x000F, 
	MAP_03_BASE + 0x0024, MAP_03_BASE + 0x0057, 
	MAP_03_BASE + 0x0074, MAP_03_BASE + 0x00AA, 
	MAP_03_BASE + 0x00BE, MAP_03_BASE + 0x00E7, 
	MAP_03_BASE + 0x0130, MAP_03_BASE + 0x018B, 
	MAP_03_BASE + 0x01B5, MAP_03_BASE + 0x01CE, 
	MAP_03_BASE + 0x01F9, MAP_03_BASE + 0x021D, 
	MAP_03_BASE + 0x023B, MAP_03_BASE + 0x0288, 
	MAP_03_BASE + 0x02D1, MAP_03_BASE + 0x0318, 
	MAP_03_BASE + 0x0363, MAP_03_BASE + 0x03A0, 
	MAP_03_BASE + 0x03D6, MAP_03_BASE + 0x03F6, 
	MAP_03_BASE + 0x0440, MAP_03_BASE + 0x0496
};

// Total screens size in bytes is 1214

// Locks
// These tiles are locks:  15
const unsigned char map_03_locks [] = {
	0x09, 0x63, 0x06, 0x7c, 0x0e, 0x54, 0x15, 0x94
};

// Map # 4 read from level4.map (3x4)

// Definitions

#define MAP_04_CHRROM    2
#define MAP_04_BASE      0x0000
#define MAP_04_W         3
#define MAP_04_H         4
#define MAP_04_MAXPANTS  12

// Screens index

const unsigned int map_04_scr_offsets [] = {
	MAP_04_BASE + 0x0000, MAP_04_BASE + 0x006D, 
	MAP_04_BASE + 0x00D1, MAP_04_BASE + 0x0137, 
	MAP_04_BASE + 0x01B5, MAP_04_BASE + 0x021F, 
	MAP_04_BASE + 0x028C, MAP_04_BASE + 0x02F8, 
	MAP_04_BASE + 0x0375, MAP_04_BASE + 0x03E8, 
	MAP_04_BASE + 0x044B, MAP_04_BASE + 0x04A8
};

// Total screens size in bytes is 1314

// Map # 5 read from level5.map (6x4)

// Definitions

#define MAP_05_CHRROM    2
#define MAP_05_BASE      0x0522
#define MAP_05_W         6
#define MAP_05_H         4
#define MAP_05_MAXPANTS  24

// Screens index

const unsigned int map_05_scr_offsets [] = {
	MAP_05_BASE + 0x0000, MAP_05_BASE + 0x0057, 
	MAP_05_BASE + 0x0090, MAP_05_BASE + 0x00C6, 
	MAP_05_BASE + 0x0100, MAP_05_BASE + 0x0127, 
	MAP_05_BASE + 0x0199, MAP_05_BASE + 0x01D8, 
	MAP_05_BASE + 0x0221, MAP_05_BASE + 0x0262, 
	MAP_05_BASE + 0x02B7, MAP_05_BASE + 0x02FB, 
	MAP_05_BASE + 0x0357, MAP_05_BASE + 0x03BA, 
	MAP_05_BASE + 0x0405, MAP_05_BASE + 0x0459, 
	MAP_05_BASE + 0x04BA, MAP_05_BASE + 0x0501, 
	MAP_05_BASE + 0x0575, MAP_05_BASE + 0x05C8, 
	MAP_05_BASE + 0x062E, MAP_05_BASE + 0x0680, 
	MAP_05_BASE + 0x06B1, MAP_05_BASE + 0x0713
};

// Total screens size in bytes is 1890

// Locks
// These tiles are locks:  15
const unsigned char map_05_locks [] = {
	0x0d, 0x76, 0x0e, 0x8d, 0x0f, 0x8f
};

// Map # 6 read from level6.map (6x4)

// Definitions

#define MAP_06_CHRROM    2
#define MAP_06_BASE      0x0C84
#define MAP_06_W         6
#define MAP_06_H         4
#define MAP_06_MAXPANTS  24

// Screens index

const unsigned int map_06_scr_offsets [] = {
	MAP_06_BASE + 0x0000, MAP_06_BASE + 0x0087, 
	MAP_06_BASE + 0x00F6, MAP_06_BASE + 0x0147, 
	MAP_06_BASE + 0x01B9, MAP_06_BASE + 0x021F, 
	MAP_06_BASE + 0x0288, MAP_06_BASE + 0x02E0, 
	MAP_06_BASE + 0x032F, MAP_06_BASE + 0x0398, 
	MAP_06_BASE + 0x0419, MAP_06_BASE + 0x048E, 
	MAP_06_BASE + 0x04F5, MAP_06_BASE + 0x055B, 
	MAP_06_BASE + 0x05BC, MAP_06_BASE + 0x0630, 
	MAP_06_BASE + 0x06B2, MAP_06_BASE + 0x0718, 
	MAP_06_BASE + 0x077A, MAP_06_BASE + 0x07D4, 
	MAP_06_BASE + 0x083A, MAP_06_BASE + 0x0897, 
	MAP_06_BASE + 0x08E2, MAP_06_BASE + 0x093C
};

// Total screens size in bytes is 2432

// Locks
// These tiles are locks:  15
const unsigned char map_06_locks [] = {
	0x05, 0xa4, 0x09, 0x2f, 0x0a, 0xa5
};

// Map # 7 read from level7.map (9x3)

// Definitions

#define MAP_07_CHRROM    2
#define MAP_07_BASE      0x1604
#define MAP_07_W         9
#define MAP_07_H         3
#define MAP_07_MAXPANTS  27

// Screens index

const unsigned int map_07_scr_offsets [] = {
	MAP_07_BASE + 0x0000, MAP_07_BASE + 0x006F, 
	MAP_07_BASE + 0x00B8, MAP_07_BASE + 0x00FA, 
	MAP_07_BASE + 0x0143, MAP_07_BASE + 0x0195, 
	MAP_07_BASE + 0x01EB, MAP_07_BASE + 0x025E, 
	MAP_07_BASE + 0x02C2, MAP_07_BASE + 0x0316, 
	MAP_07_BASE + 0x033E, MAP_07_BASE + 0x03AC, 
	MAP_07_BASE + 0x0421, MAP_07_BASE + 0x0474, 
	MAP_07_BASE + 0x04C8, MAP_07_BASE + 0x050E, 
	MAP_07_BASE + 0x054C, MAP_07_BASE + 0x05AD, 
	MAP_07_BASE + 0x0619, MAP_07_BASE + 0x0653, 
	MAP_07_BASE + 0x06A5, MAP_07_BASE + 0x06E8, 
	MAP_07_BASE + 0x072D, MAP_07_BASE + 0x0772, 
	MAP_07_BASE + 0x07B4, MAP_07_BASE + 0x07F3, 
	MAP_07_BASE + 0x0835
};

// Total screens size in bytes is 2252

