// Patterns, tiles, metatiles, and maybe dragons. Generated by mkts
// Copyleft 2017 The Mojon Twins

#define STRINGS_OFFSET_TEXTS 0x00
 
// Strings
 
// Skipped line { 0x00, 0x53, 0x54, 0x55, 0x56, 0x57, 0x58, 0x59, 0x5a, 0x5b, 0x5c, 0xff };
 
// Strings index
 
const unsigned char *strs_texts [] = {
	
};
 
// 92 patterns extracted. Next = 92
 
