// Patterns, tiles, metatiles, and maybe dragons. Generated by mkts
// Copyleft 2017 The Mojon Twins

// Tileset tilemaps & pals generated by mkts [nes mode]
// Copyleft 2017 The Mojon Twins
 
const unsigned char tsstars_pals [] = {
	0x03, 0x02
};

const unsigned char tsstars_tmaps [] = {
	0xd6, 0xd7, 0xd8, 0xd9, 
	0xda, 0xdb, 0xdc, 0xdd
};

